Bump SZ3 to v3.2.1 + add support for NoPrediction and Lossless compression
apertus-open-source-cinema/sz3-rs pull request #8
Opened 2024-12-07 09:22 UTC by juntyr

The `ALGO_NOPRED` and `ALGO_LOSSLESS` compression modes are, granted, not very useful in most circumstances. Lossless just runs the lossless stage on the data, and no prediction only runs the quantizer + encoder + lossless stages. I'd like to just use SZ3's (prediction) error encoding, for which the no prediction mode is perfect.

If the PR looks good to you @rroohhh, perhaps you could also publish a new release (which then also includes the SZ3 v3.2.1 bump)?

2024-12-07 09:36 UTC, juntyr commented
It seems that https://github.com/szcompressor/SZ3/commit/8a6220da6517db0f9abbd63e7c7260365357dff5 removed the interpolation block size config parameter and just replaced it with constant 32 in the code.

2024-12-07 10:01 UTC, juntyr commented
I have no idea why the lossless mode fails but it seems to be an issue on the S3 side that I don't feel like dealing with. So let's see if just the NoPrediction mode would work (especially since the lossless mode is just Zstd with nothing else)

2024-12-07 12:19 UTC, juntyr commented
Ok, https://github.com/szcompressor/SZ3/commit/9bd968ff4a087491bd5586af0aae891fc0f52681 made it so that SZ3 can sometimes internally override the compression algorithm to lossless, so we need to support it in some way.

However, compress -> decompress tests with the lossless algorithm crash in C++ on an assertion that the decompressed array has the same size as the original data. I have no idea why this happens and it seems it's an SZ3 issue.

So for now, I've made the lossless compression mode non-constructible. That way, you cannot set it manually for encoding, but if SZ3 decides internally to use it, you can observe that it did during decoding.

2024-12-08 08:05 UTC, juntyr commented
I found the bug in SZ3 - asking for lossless compression with a non-zero error bound resulted in no compression actually taking place (i.e. only the config was encoded but no data). I've submitted https://github.com/szcompressor/SZ3/pull/69 to fix the issue.

To test the patch, I'm applying the fix in sz3-rs directly right now. If the tests pass, this could either be merged directly or we could wait until the upstream patch is merged first.

2024-12-08 13:31 UTC, juntyr commented
Ok, SZ3 has fixed the bug upstream in https://github.com/szcompressor/SZ3/commit/29234fd919b87ab7f951d519314900f9066f9f07, so this PR should be good to go now :)

2024-12-08 14:01 UTC, rroohhh requested changes

2024-12-08 14:01 UTC, rroohhh commented on src/lib.rs
> +                }
Should this not assert something like `psnr == 0` for the lossless mode?
What `psnr` does the `NoPrediction` mode produce? If I understand it correctly that should still produce a `psnr` below the specified bound, but just yield worse compression, because the prediction step is skipped?

2024-12-08 16:02 UTC, juntyr commented on src/lib.rs
> +                }
Good catch! The problem case was the lossless one (whether explicitly specified or automatically triggered by SZ3), since PSNR(MSE=0) = +inf. I updated the check to be error-bound mode independent and succeed if either MSR==0 or PNSR < bound. I also added a separate check that all items bit-reproducibly roundtrip for the lossless mode.

2024-12-09 15:41 UTC, rroohhh approved these changes

2024-12-09 16:13 UTC, merged

2024-12-09 16:16 UTC, rroohhh commented
Thank you for your contribution. I just published a new version to crates.io that includes your changes.